/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ricdotnet.guessinggame;

import java.util.*;
/**
 *
 * @author Ricardo Rocha
 */
public class GuessingGame {
    
    static Scanner input = new Scanner(System.in);
    static Random rand = new Random();
    static int cpu;
    static int user;
    static boolean finished = false;
    
    //method to generate a new random cpu number
    public static int cpuNumber(){
        return cpu = rand.nextInt(100);
    }
    
    //method to ask the user for an input
    public static int userGuess(){
        System.out.println("Enter a number (0-100): ");
        user = input.nextInt();
        return user;
    }
    
    //main method start
    public static void main(String[] args){
        
        System.out.println("##### FIND THE CPU NUMBER ##### \n"
                + "In this game you have to find out the number \n"
                + "generated by the program. From 0 to 100.");
        
        System.out.println();
        System.out.println("The cpu guess is **.");
        
        cpuNumber(); //generate a new cpu number
        userGuess(); //ask user for a number
        
        while(finished == false){
            if(user > cpu){
                System.out.println("Your guess is higher than the cpu. \n"
                        + "Please try again: ");
                user = input.nextInt();
            }else if(user < cpu){
                System.out.println("Your guess is lower than the cpu. \n"
                        + "Please try again: ");
                user = input.nextInt();
            }else{
                System.out.println("Congratulations. Your guessed it!!! \n"
                        + cpu + " was the golden number.");
                finished = true;
            }
        }//end while loop
        
        System.out.println("Thanks for playing. :)");
        
    }//end main method
    
}//end main class
